export type PolicyBlock =
    | { type: "paragraph"; text: string }
    | { type: "bullets"; items: string[] };

export type PolicySection = {
    id: string;
    title: string;
    blocks: PolicyBlock[];
};

export type PrivacyPolicyPageData = {
    title: string;
    lastUpdated: string;
    intro: string;

    sections: PolicySection[];

    cta: {
        title: string;
        buttonLabel: string;
        href: string;
        image: { src: string; alt: string };
    };
};

export const privacyPolicyData: PrivacyPolicyPageData = {
    title: "Privacy Policy",
    lastUpdated: "Last updated: 01 February 2026",
    intro: "This Privacy Policy describes the policies and procedures of Beyond Code on the collection, use, and disclosure of your information when you use our services and website. It also tells you about your privacy rights and how applicable laws protect you.",

    sections: [
        {
            id: "interpretation",
            title: "Interpretation",
            blocks: [
                {
                    type: "paragraph",
                    text: "Words with capitalized initials have meanings defined under the following conditions. These definitions apply regardless of whether they appear in singular or plural form.",
                },
            ],
        },
        {
            id: "definitions",
            title: "Definitions",
            blocks: [
                {
                    type: "paragraph",
                    text: "For the purposes of this Privacy Policy:",
                },
                {
                    type: "bullets",
                    items: [
                        "Account means a unique account created for You to access our Service or parts of our Service.",
                        "Company refers to Beyond Code (“We”, “Us” or “Our”).",
                        "Cookies are small files placed on Your device by a website.",
                        "Country refers to the country where Beyond Code operates.",
                        "Device means any device that can access the Service such as a computer, a cellphone or a tablet.",
                        "Personal Data is any information that relates to an identified or identifiable individual.",
                        "Service refers to the Website and related services.",
                        "Service Provider means any natural or legal person who processes the data on behalf of the Company.",
                        "Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
                    ],
                },
            ],
        },
        {
            id: "collecting",
            title: "Collecting and Using Your Personal Data",
            blocks: [
                { type: "paragraph", text: "Types of Data Collected" },
                {
                    type: "paragraph",
                    text: "While using our Service, we may ask you to provide certain personally identifiable information that can be used to contact or identify you.",
                },
                {
                    type: "bullets",
                    items: [
                        "First name and last name",
                        "Email address",
                        "Phone number",
                        "Address, city, state/province, ZIP/postal code",
                    ],
                },
                { type: "paragraph", text: "Usage Data" },
                {
                    type: "paragraph",
                    text: "Usage Data is collected automatically when using the Service and may include information such as your device’s IP address, browser type, browser version, pages visited, and time and date of your visit.",
                },
            ],
        },
        {
            id: "tracking",
            title: "Tracking Technologies and Cookies",
            blocks: [
                { type: "paragraph", text: "Types of Cookies We Use" },
                {
                    type: "bullets",
                    items: [
                        "Necessary / Essential Cookies — required to provide the Service.",
                        "Cookies Policy / Notice Acceptance Cookies — to identify if users have accepted cookies.",
                        "Functionality Cookies — to remember choices you make and provide a more personal experience.",
                    ],
                },
            ],
        },
        {
            id: "use",
            title: "Use of Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "We may use Personal Data for the following purposes:",
                },
                {
                    type: "bullets",
                    items: [
                        "To provide and maintain our Service",
                        "To manage your Account and registrations",
                        "To contact you via email, phone, or other electronic communications",
                        "To provide updates and relevant information (unless you opt out)",
                        "To manage requests and support",
                        "For data analysis, service improvement, and effectiveness measurement",
                    ],
                },
            ],
        },
        {
            id: "sharing",
            title: "Sharing of Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "We may share your Personal Data in the following situations:",
                },
                {
                    type: "bullets",
                    items: [
                        "With Service Providers to monitor and analyze the use of our Service",
                        "For business transfers (merger, acquisition, or asset sale)",
                        "With affiliates and partners, under this Privacy Policy",
                        "With your consent or at your direction",
                    ],
                },
            ],
        },
        {
            id: "retention",
            title: "Retention of Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "We retain your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements.",
                },
            ],
        },
        {
            id: "transfer",
            title: "Transfer of Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "Your information may be processed and stored in locations where our Service Providers operate. We take reasonable steps to ensure appropriate safeguards are in place.",
                },
            ],
        },
        {
            id: "delete",
            title: "Delete Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "You have the right to request deletion of your Personal Data. You may update or delete your information through your Account settings or by contacting us.",
                },
            ],
        },
        {
            id: "disclosure",
            title: "Disclosure of Your Personal Data",
            blocks: [
                { type: "paragraph", text: "Business Transactions" },
                {
                    type: "paragraph",
                    text: "If the Company is involved in a merger, acquisition or asset sale, your Personal Data may be transferred.",
                },
                {
                    type: "paragraph",
                    text: "Law Enforcement and Legal Requirements",
                },
                {
                    type: "bullets",
                    items: [
                        "Comply with legal obligations",
                        "Protect the rights or property of the Company",
                        "Prevent wrongdoing related to the Service",
                        "Protect the personal safety of users or the public",
                        "Protect against legal liability",
                    ],
                },
            ],
        },
        {
            id: "security",
            title: "Security of Your Personal Data",
            blocks: [
                {
                    type: "paragraph",
                    text: "We take commercially reasonable measures to protect Personal Data. However, no method of transmission over the Internet or electronic storage is 100% secure.",
                },
            ],
        },
        {
            id: "children",
            title: "Children’s Privacy",
            blocks: [
                {
                    type: "paragraph",
                    text: "Our Service does not address anyone under the age of 13. We do not knowingly collect Personal Data from children under 13.",
                },
            ],
        },
        {
            id: "links",
            title: "Links to Other Websites",
            blocks: [
                {
                    type: "paragraph",
                    text: "Our Service may contain links to third-party websites not operated by us. We are not responsible for their content, privacy policies, or practices.",
                },
            ],
        },
        {
            id: "changes",
            title: "Changes to This Privacy Policy",
            blocks: [
                {
                    type: "paragraph",
                    text: "We may update this Privacy Policy from time to time. Changes are posted on this page with an updated “Last updated” date.",
                },
            ],
        },
        {
            id: "contact",
            title: "Contact Us",
            blocks: [
                {
                    type: "paragraph",
                    text: "If you have any questions about this Privacy Policy or our data practices, please contact us:\nEmail: info@beyondcode.co",
                },
            ],
        },
    ],

    cta: {
        title: "Transform Your Operations\nwith Intelligence",
        buttonLabel: "Book for Consultation",
        href: "#",
        image: { src: "/privacy/cta.jpg", alt: "AI in operations" },
    },
};
